### ISSUE TITLE
hook System Framework

### ISSUE THREAD

**Issue by 006hjy** [chiteroman/AttestationSpoofer#3]
How to hook the system framework,Have the system clock return to the application that the bootloader is locked

**Comment by chiteroman** [comment]
I didn't understand it very well, but if you want to fake the bootloader status you have to activate the application in the list.

**Comment by 006hjy** [comment]
App asks the system: Is your bl locked?We're going to kidnap the system.Let the system tell APP that it is locked.So you don't need kidnapping software.Kidnapping is the hook.

**Comment by chiteroman** [comment]
If you hook system framework, you will change the method only for system and not for apps. Because we are hooking an APEX java class: https://source.android.com/docs/core/ota/apex we can't affect all apps. The only way is like Smali Patcher do, pull the conscrypt.jar, modify the method, compile it and try to change it in boot with Magisk. I'm trying to inject an apk with https://github.com/canyie/pine to hook all the required methods without using Xposed.

**Comment by chiteroman** [comment]
The another way is using a custom ROM
